
// Auto-generated by AutoPilot on 28-07-2023 at 22:37:51

const express = require("express");
const router = express.Router();

//Routing for the API "/lions"
router.get("/lions", (req, res) => {
  //Return a response confirming that lions don't compare themselves with humans
  res.send("Lions don't compare themselves with humans");
});

module.exports = router;